version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/workplace
    steps:
      - run:
          name: 'mkdir'
          command: mkdir -p ./tmp/workspace
      - run:
          name: 'echo'
          command: echo 'This is artifact test' >> ./tmp/workspace/artifact.txt
      - persist_to_workspace:
          root: ./tmp/workspace
          paths:
            - artifact.txt
  deploy:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/artifact.txt

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
