version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'pwd'
      - run: 'ls'
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "tests/package.json" }}
      - run:
          name: 'yarn'
          working_directory: tests
          command: yarn
      - save_cache:
          paths:
            - tests/node_modules
          key: yarn-dependencies-{{ checksum "tests/package.json" }}
      - run:
          name: install fonts
          command: |
            sudo apt-get update
            sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho
      - attach_workspace:
          at: ./tests/visual_regression/src
      - run:
          name: 'ls'
          command: ls /tests/visual_regression
      - run:
          name: 'ls'
          command: ls /tests/visual_regression/src
      - run:
          name: 'copy reference to workspace'
          working_directory: tests/visual_regression/
          command: |
            directory=/tests/src/reference
            if [ -z "$(ls $directory)" ]; then
              yarn ref
            else
              cp -r /tests/src/reference/ ./src/reference
            fi
      - run:
          name: 'yarn test'
          working_directory: tests
          command: |
            yarn test || echo "check the difference"
      - store_artifacts:
          path: tests/src/tests
          destination: tests
      - store_artifacts:
          path: tests/src/reference/
          destination: reference
      - store_artifacts:
          path: tests/src/html_report
          destination: html_report
      - store_test_results:
          path: tests/src/ci_report
      - persist_to_workspace:
          root: ./tests/visual_regression/src
          paths:
            - reference
            - tests
  test:
    docker:
      - image: circleci/node:10.15.0
    working_direcotry: ~/repo
    steps:
      - checkout
      - run: mkdir -p ./tests/visual_regression
      - run: echo 'This is artifact' >> ./tests/visual_regression/artifact.txt
      - run: cat ./tests/visual_regression/artifact.txt
      - run: mkdir -p ./tests/visual_regression/hoge
      - persist_to_workspace:
         root: ./tests/visual_regression
         paths:
           - artifact.txt
           - hoge
  next-test:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - run: ls ./tests/visual_regression
      - attach_workspace:
          at: ./tests/visual_regression
      - run: cat ./tests/visual_regression/artifact.txt
      - run: ls ./tests/visual_regression
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - next-test:
          requires:
            - test
