version: 2
jobs:

  build:
    docker:
      - image: circleci/node:10.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'pwd'
      - run: 'ls'
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "tests/package.json" }}
      - run:
          name: 'yarn'
          working_directory: tests
          command: yarn
      - save_cache:
          paths:
            - tests/node_modules
          key: yarn-dependencies-{{ checksum "tests/package.json" }}
      - run:
          name: install fonts
          command: |
            sudo apt-get update
            sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho
      - attach_workspace:
          at: /tests/src
      - run:
          name: 'copy reference to workspace'
          working_directory: tests/visual_regression/
          command: 'cp -r /tests/src/reference/ ./src/reference'
      - run:
          name: 'yarn test'
          working_directory: tests
          command: 'yarn test'
      - store_artifacts:
          path: tests/src/tests
          destination: tests
      - store_artifacts:
          path: tests/src/reference/
          destination: reference
      - store_artifacts:
          path: tests/src/html_report
          destination: html_report
      - store_test_results:
          path: tests/src/ci_report
      - persist_to_workspace:
          root: ./tests/src
          paths:
            - reference
            - tests
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
