version: 2
jobs:

  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'pwd'
      - run: 'ls'
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - tests/node_modules
          key: yarn-dependencies-{{ checksum "package.json" }}
      - run:
          name: install fonts
          command: |
            sudo apt-get update
            sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho
      - run:
          name: 'yarn ref'
          working_directory: tests
          command: 'yarn ref'
      - run:
          name: 'yarn test'
          working_directory: tests
          command: 'yarn test'
      - store_artifacts:
          path: tests/test
          destination: test
      - store_artifacts:
          path: tests/reference/
          destination: reference
      - store_artifacts:
          path: tests/html_report
          destination: html_report
      - store_test_results:
          path: tests/ci_report
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
